### ISSUE TITLE
Numpy 1.24 removes support for type aliases

### ISSUE THREAD

**Issue by willsthompson** [LBL-EESA/fastkde#13]
[Numpy 1.24](https://github.com/numpy/numpy/releases/tag/v1.24.0) removes support for type aliases used in fastkde ([deprecation began in 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations))

>The deprecation for the aliases np.object, np.bool, np.float,
np.complex, np.str, and np.int is expired (introduces NumPy
1.20). Some of these will now give a FutureWarning in addition to
raising an error since they will be mapped to the NumPy scalars in
the future.

Usage now raises an AttributeError.

**Comment by taobrienlbl** [comment]
@willsthompson - PR #12 fixes this issue, and a new release has been published to pypi.  Doing `pip install fastkde --upgrade` should bring you up to date.  Does that fix the issue?

**Comment by willsthompson** [comment]
@taobrienlbl yes, it does! Thank you for getting this fix out so quickly!

**Comment by taobrienlbl** [comment]
great, glad to hear, and that was thanks to @al-jshen for submitting the PR!
