### ISSUE TITLE
Output the corresponding frequency based on the data sample instead of a normalized PDF？

### ISSUE THREAD

**Issue by swenqing** [LBL-EESA/fastkde#18]
Dear author, Your package is a great inspiration to me. When I was researching recently, it appeared that multidimensional data needs its frequency (like a histogram) instead of PDF. I would like to ask if your package can fulfill such an offer, and how? the package can implement such as ‘np.histogramdd’ directly output the corresponding frequency function?

**Comment by taobrienlbl** [comment]
Hi @swenqing - sorry it took so long to get back to you.  This package implements a specific method for estimating PDFs: kernel density estimation.  Histograms are another way to estimate PDFs, and adding histogram functionality is out of scope of this package.

If my response doesn't seem to answer your question, please feel free to reopen this.

Cheers
