### ISSUE TITLE
upload to pypi fails in github actions

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/fastkde#22]
Upload to pypi fails in github actions with a series of messages along the lines of the following (logs attached here: [logs_9.zip](https://github.com/LBL-EESA/fastkde/files/11326367/logs_9.zip)):

```
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 148.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 148.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 148.9 MB/s
25hWARNING  Received "502: Bad Gateway"                                            
         Package upload appears to have failed. Retry 4 of 5.                   
Uploading fastkde-0.0.0-cp36-cp36m-macosx_10_9_x86_64.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/245.1 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.1/245.1 kB • 00:00 • 149.9 MB/s
25hWARNING  Received "502: Bad Gateway"                                            
         Package upload appears to have failed. Retry 5 of 5.                   
WARNING  Error during upload. Retry with the --verbose option for m
[logs_9.zip](https://github.com/LBL-EESA/fastkde/files/11326363/logs_9.zip)
ore details. 
ERROR    HTTPError: 502 Bad Gateway from https://upload.pypi.org/legacy/        
         Bad Gateway         
```

@davidt0x - have you come across this recently?  Wondering if this is a transient network problem--though https://status.python.org/ doesn't seem to show anything.  One thing that stands out is that the version number is being set to 0.0.0 for several of the .whl files, though I'm not sure whether that's related.

**Comment by davidt0x** [comment]
Ok, I think there are two unrelated issues. The failed upload I think is just bad luck with pypi. I checked earlier as well and status appeared fine but it seems like things have changed. Here are the most recent notes from https://status.python.org/ 

_Monitoring - Our object storage provider has recovered from the outage and we are monitoring for any regressions._
_Apr 25, 2023 - 21:51 UTC_

_Identified - Our object storage provider is currently experiencing an outage, causing PyPI uploads to fail._
_Apr 25, 2023 - 20:44 UTC_

The issue with wheel files that have 0.0.0 for version I think are all python 3.6. It is probably because setuptool_scm has dropped python 3.6 support. I will submit yet another PR to disable Python 3.6 wheels completely.

**Comment by taobrienlbl** [comment]
It's never just one thing is it...

(Maybe we should by lotto tickets.)

Thanks for checking on that again.  Good to know we should just be able to wait.  The 3.6 issue isn't urgent from my perspective though: was just making observations.

Thanks again...having wheels build automatically for fastKDE is just awesome.

**Comment by davidt0x** [comment]
Just did a PR #23 for the 3.6 issue. I suspect if we don't fix now we will run into trouble later with uploads because there will already be wheels present with 0.0.0 version number and we might get an error next time. Third time is the charm!

**Comment by taobrienlbl** [comment]
meant to confirm @davidt0x  - this did work.  Thanks so much!
