### ISSUE TITLE
Score samples function

### ISSUE THREAD

**Issue by simonpedrogonzalez** [LBL-EESA/fastkde#4]
Is there a way to score samples with natural or log density estimate?

**Comment by taobrienlbl** [comment]
Hi @simonpedrogonzalez -- glad that fastKDE might be of interest!

I'm not certain I understand what you're asking.  Are you asking about weighting the samples prior to performing the KDE?  If so, then no, that capability doesn't yet exist.

If you're talking about taking the log of the samples prior to performing the KDE, then yes, that does.  You can use the `logAxes=True` option for that.

**Comment by aleksyprok** [comment]
Hi @taobrienlbl. Are you planning on adding the ability to weigh the samples prior to performing the KDE?

**Comment by taobrienlbl** [comment]
Hi @aleksyprok - thanks for reaching out.  I don't have concrete plans to add this feature.  It's something that I have considered.  I anticipate that the implementation would be relatively easy, but I would want to make sure it's done in a way that maintains the optimality of the unweighted fastKDE method.  That will take some theoretical work (and is likely worth writing a paper on).
