### ISSUE TITLE
Bandwidth?

### ISSUE THREAD

**Issue by MarcelRobitaille** [LBL-EESA/fastkde#6]
Is there a bandwidth options like `bw_method` of `scipy.stats.gaussian_kde`?

**Comment by taobrienlbl** [comment]
Hi @MarcelRobitaille -- glad to hear of your interest in fastKDE.  No, there isn't a bandwidth option, since fastKDE uses an approach that selects an optimal bandwidth (and kernel shape) based on the data being passed in.

Is there something you're trying to work around or fix in this case?

**Comment by MarcelRobitaille** [comment]
Hi @taobrienlbl. I see. We are using this as part of a bigger algorithm, and previously we used `bw_method` as a tuning parameter. That is, we had to adjust the value depending on the specific example, but if fastKDE automatically finds the "optimal" bandwidth, then probably it is fine. Indeed, I have not noticed any issues yet, but I only switched recently.

**Comment by taobrienlbl** [comment]
Great, glad to hear!  I hope it continues to work well for you--I'd be happy to chat further if you encounter issues.

Cheers~
